### ISSUE TITLE
Installation depuis un poste Linux

### ISSUE THREAD

**Issue by Seikomi** [Sw4T/GrooveBerry#1]
Je n'arrive toujours pas à faire fonctionner le client depuis la branche Master, est que quelqu'un pourrai vérifier qu'il arrive bien à installer le projet from scratch (en suivant la provédure du README) et que le probleme vient de chez moi.
Merci.

**Comment by Bambiche** [comment]
Je vais le faire ce soir(ce sera sous windows par contre^^)

**Comment by Sw4T** [comment]
Soit t'es mauvais en android soit j'ai zappé un truc ahahah, je test ça ce week-end sur un linux np

      De : Nicolas Symphorien <notifications@github.com>
 À : Sw4T/GrooveBerry <GrooveBerry@noreply.github.com> 
 Envoyé le : Vendredi 22 mai 2015 13h50
 Objet : [GrooveBerry] Installation depuis un poste Linux (#1)
   
Je n'arrive toujours pas à faire fonctionner le client depuis la branche Master, est que quelqu'un pourrai vérifier qu'il arrive bien à installer le projet from scratch (en suivant la provédure du README) et que le probleme vient de chez moi.
Merci.—

**Comment by Seikomi** [comment]
Merci, le soucie semble venir de mon coté, sorry !
